name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 15.157.72.204
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/merge2ownapi"
        debug: true

    - name: Run deployment script on EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 15.157.72.204
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/merge2ownapi
          git pull
          npm install
          pm2 restart all
  
